<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.bgsoftware</groupId>
        <artifactId>WildTools</artifactId>
        <version>2025.2</version>
    </parent>

    <artifactId>WildTools-Hooks</artifactId>
    <packaging>pom</packaging>

    <name>WildTools-Hooks</name>

    <modules>
        <module>ChunkCollectors</module>
        <module>ChunkHoppers</module>
        <module>FactionsUUID</module>
        <module>FactionsX</module>
        <module>Folia</module>
        <module>GriefPrevention</module>
        <module>Lands</module>
        <module>MassiveFactions</module>
        <module>McMMO1</module>
        <module>McMMO2</module>
        <module>MergedSpawner</module>
        <module>Residence</module>
        <module>RoseStacker</module>
        <module>SavageFactions</module>
        <module>SilkSpawners_CandC2</module>
        <module>SilkSpawners_Timbru5</module>
        <module>SilkSpawners_Timbru6</module>
        <module>SuperMobCoins</module>
        <module>Towny</module>
        <module>Vault</module>
        <module>Villagers</module>
        <module>WildChests</module>
        <module>WildStacker</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>com.bgsoftware</groupId>
            <artifactId>WildToolsAPI</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
